### PR TITLE
Add make targets to download templates

### PR DESCRIPTION
**Pull request by Akeshihiro**

### CODE REVIEW

**Comment by cagix** [comment]
@Akeshihiro thanks for your contribution :)  

before hitting the "merge" button, i'd like to discuss a few questions/ideas:
- the new make targets `eisvogel-dl` and `cleanthesis-dl`look like duplicated code. i'm wondering if both targets could be unified into a single "`template-dl`" target using neutral variables. however, the `eisvogel` (as well as the `cleanthesis`) target would need to set these variables then ...
- in your pr the `eisvogel` (as well as the `cleanthesis`) target would download the template each time, even the template exists already (due to `.PHONY`). imho both targets need to depend on their template file itself and not the download target?
- `make distclean` should also remove any template file.
- do we really need `TEMPLATES_DIR` and `EISVOGEL_DIR` and `CLEANTHESIS_DIR`? after "installing" the template the whole `TMP_DIR` gets deleted (well, at least in `make clean`) ...

**Comment by cagix** [comment]
hmmm, maybe we should delete the `TMP_DIR` after `eisvogel-dl` ... otherwise users could see a repo inside a repo, which could be confusing?

**Comment by cagix** [comment]
proposal: 

1. `eisvogel` depends on `eisvogel.tex`, `cleanthesis` on `cleanthesis.sty`
2. new targets `eisvogel.tex` and `cleanthesis.sty` would set variables for `template-dl` and also depend on  `template-dl`

this way, `make eisvogel` would run directly if the template already exists. otherwise the dependent target `eisvogel.tex` would be called, which would set the variables and call its dependent target `template-dl`, which in turn downloads the template file and copies it to the right place and then deletes the `TMP_DIR` folder.

could this work?

**Comment by Akeshihiro** [comment]
thank you for your feedback! well, I've refactored the code according to your ideas. it was a little tricky to force make to not download the templates everytime, but at the end I found a solution that does the job.

imho the TMP_DIR variable is not that bad if you think of it in the way of a build directory. maybe it would be better to rename the variable to BUILD_DIR or something like this.

if you wish I will implement further optimizations later.

**Comment by cagix** [comment]
looks good to me :)  thanks!

**Pull request merged**
